loc_ihm_location:
    resource: "@LocIHMLocationBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/
    requirements:
        _locale: fr|en

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix: /{_locale}
    requirements:
        _locale: fr|en