loc_ihm_location_vehicule:
    resource: "@LocIHMLocationBundle/Resources/config/routing/vehicule.yml"
    prefix:   /admin/vehicule

loc_ihm_location_typevehicule:
    resource: "@LocIHMLocationBundle/Resources/config/routing/typevehicule.yml"
    prefix:   /admin/typevehicule

loc_ihm_location_forfait:
    resource: "@LocIHMLocationBundle/Resources/config/routing/forfait.yml"
    prefix:   /admin/forfait

loc_ihm_location_contrat:
    resource: "@LocIHMLocationBundle/Resources/config/routing/contrat.yml"
    prefix:   /admin/contrat

loc_ihm_location_agence:
    resource: "@LocIHMLocationBundle/Resources/config/routing/agence.yml"
    prefix:   /admin/agence

loc_ihm_location_admin:
    resource: "@LocIHMLocationBundle/Resources/config/routing/admin.yml"
    prefix: /admin

loc_ihm_location_homepage:
    path:     /
    defaults: { _controller: LocIHMLocationBundle:Default:index}