services:
    locihm_location.registration.form.type:
        class: LocIHM\LocationBundle\Form\Type\RegistrationFormType
        tags:
            - { name: form.type, alias: locihm_location_registration }
