typevehicule:
    path:     /
    defaults: { _controller: "LocIHMLocationBundle:TypeVehicule:index" }

typevehicule_show:
    path:     /{id}/show
    defaults: { _controller: "LocIHMLocationBundle:TypeVehicule:show" }

typevehicule_new:
    path:     /new
    defaults: { _controller: "LocIHMLocationBundle:TypeVehicule:new" }

typevehicule_create:
    path:     /create
    defaults: { _controller: "LocIHMLocationBundle:TypeVehicule:create" }
    methods:  POST

typevehicule_edit:
    path:     /{id}/edit
    defaults: { _controller: "LocIHMLocationBundle:TypeVehicule:edit" }

typevehicule_update:
    path:     /{id}/update
    defaults: { _controller: "LocIHMLocationBundle:TypeVehicule:update" }
    methods:  [POST, PUT]

typevehicule_delete:
    path:     /{id}/delete
    defaults: { _controller: "LocIHMLocationBundle:TypeVehicule:delete" }
    methods:  [POST, DELETE]
